// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {generator} from '../models';
import {database} from '../models';
import {detect} from '../models';

export function CleanConfig():Promise<void>;

export function EditGeneratorOption(arg1:generator.Option):Promise<void>;

export function GenerateFrontendCode(arg1:string,arg2:string):Promise<string>;

export function GenerateGrpcCode(arg1:string):Promise<string>;

export function GenerateRestCode(arg1:string):Promise<string>;

export function GetDBConfig():Promise<database.DBConfig>;

export function GetDatabaseTables(arg1:database.DBConfig):Promise<Array<database.TableInfo>>;

export function GetGeneratorOptions():Promise<Array<generator.Option>>;

export function GetProjectInfo():Promise<detect.ProjectInfo>;

export function GetTableColumns(arg1:database.DBConfig,arg2:string):Promise<Array<database.ColumnInfo>>;

export function ImportDatabaseTables(arg1:database.DBConfig):Promise<string>;

export function ImportSqlTables(arg1:string):Promise<string>;

export function OpenProject(arg1:string):Promise<detect.ProjectInfo>;

export function SelectFolder():Promise<string>;

export function SetDBConfig(arg1:database.DBConfig):Promise<void>;

export function SetGeneratorOption(arg1:generator.GeneratorOptions):Promise<void>;

export function TestDatabaseConnection(arg1:database.DBConfig):Promise<database.ConnectionResult>;
