// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanConfig() {
  return window['go']['main']['App']['CleanConfig']();
}

export function EditGeneratorOption(arg1) {
  return window['go']['main']['App']['EditGeneratorOption'](arg1);
}

export function GenerateFrontendCode(arg1, arg2) {
  return window['go']['main']['App']['GenerateFrontendCode'](arg1, arg2);
}

export function GenerateGrpcCode(arg1) {
  return window['go']['main']['App']['GenerateGrpcCode'](arg1);
}

export function GenerateRestCode(arg1) {
  return window['go']['main']['App']['GenerateRestCode'](arg1);
}

export function GetDBConfig() {
  return window['go']['main']['App']['GetDBConfig']();
}

export function GetDatabaseTables(arg1) {
  return window['go']['main']['App']['GetDatabaseTables'](arg1);
}

export function GetGeneratorOptions() {
  return window['go']['main']['App']['GetGeneratorOptions']();
}

export function GetProjectInfo() {
  return window['go']['main']['App']['GetProjectInfo']();
}

export function GetTableColumns(arg1, arg2) {
  return window['go']['main']['App']['GetTableColumns'](arg1, arg2);
}

export function ImportDatabaseTables(arg1) {
  return window['go']['main']['App']['ImportDatabaseTables'](arg1);
}

export function ImportSqlTables(arg1) {
  return window['go']['main']['App']['ImportSqlTables'](arg1);
}

export function OpenProject(arg1) {
  return window['go']['main']['App']['OpenProject'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SetDBConfig(arg1) {
  return window['go']['main']['App']['SetDBConfig'](arg1);
}

export function SetGeneratorOption(arg1) {
  return window['go']['main']['App']['SetGeneratorOption'](arg1);
}

export function TestDatabaseConnection(arg1) {
  return window['go']['main']['App']['TestDatabaseConnection'](arg1);
}
